### PR TITLE
fix display of backoffice info for author and validators

### PR DESCRIPTION
**Pull request by monodo**

### CODE REVIEW

**Review by rbovard — CHANGES_REQUESTED** [review]
Thanks it does the job, nice approach.

When testing, I noticed an existing bug. As validator, we can see a field even if it's only visible by author because of the test at line 51 `{% if field_value.field.is_visible_by_author or field_value.field.is_visible_by_validators and is_validator %}`

I think we shoud use the same logical (visible by author and is author). Can you please adapt it?

**Comment by monodo** [comment]
Fixed

**Review by AlexandreJunod — APPROVED** [review]
Code is OK for me

**Comment by AlexandreJunod** [comment]
In PO review @rbovard 

https://jira.liip.ch/browse/YC-1080

**Review by rbovard — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
