### PR TITLE
Feature/readme

### PR DESCRIPTION
**Pull request by AlexandreJunod**

### CODE REVIEW

**Review by rbovard — DISMISSED** [review]
Thanks, I've made some changes via a commit (instead to make many code suggestions, it was faster to do so).

Feel free to adapt it.

**Comment by rbovard** [comment]
Question: maybe we should put the "Contribution guideline" after "Setting up full Docker non persistent demo" and "Setting up production instance" (--> people want to try more than contribute?). And it will be just before the "Development tools" paragraph.

What do you think?

**Comment by AlexandreJunod** [comment]
> 

It's a good idea

**Comment by AlexandreJunod** [comment]
@rbovard Good idea, I'll move this just before "Development tools"

**Pull request merged**
