### PR TITLE
yc-1093

### PR DESCRIPTION
**Pull request by AlexandreJunod**
### Updates

Prevent from creating a submission without selecting a form. User is redirected to the select form step with a comprehensive message.

Jira : https://jira.liip.ch/browse/YC-1093 
PR to delete : https://github.com/yverdon/geocity/pull/814

### CODE REVIEW

**Comment by rbovard** [comment]
It's better since the submission cannot be sent, but the exception is not handled...

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/geocity/apps/submissions/views.py", line 142, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/code/geocity/apps/submissions/views.py", line 1805, in submission_submit_confirmed
    raise SuspiciousOperation
```

For me it will be better if we consider a submission as incomplete (like if not all mandatory fields are set) if the form is not selected (so the user cannot send it, but can come back to step "Objects" to choose the form).

**Review by rbovard — CHANGES_REQUESTED** [review]
It's better since the submission cannot be sent, but the exception is not handled...

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/dist-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/code/geocity/apps/submissions/views.py", line 142, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/django/contrib/auth/decorators.py", line 23, in _wrapper_view
    return view_func(request, *args, **kwargs)
  File "/code/geocity/apps/submissions/views.py", line 1805, in submission_submit_confirmed
    raise SuspiciousOperation
```

For me it will be better if we consider a submission as incomplete (like if not all mandatory fields are set) if the form is not selected (so the user cannot send it, but can come back to step "Objects" to choose the form).

**Comment by AlexandreJunod** [comment]
image

**Review by rbovard — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
